apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wordpress
    image: wordpress:latest
    ports:
    - containerPort: 80
      name: http
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-service
    - name: WORDPRESS_DB_USER
      value: user
    - name: WORDPRESS_DB_PASSWORD
      value: password
    - name: WORDPRESS_DB_NAME
      value: wordpressdb
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "1"
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 60
      timeoutSeconds: 5  
      failureThreshold: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /wp-login.php
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 10
      failureThreshold: 3
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 20
      failureThreshold: 3
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 80
    nodePort: 30090

