apiVersion: v1  # versão da API Kubernetes para objetos core (Pods)
kind: Pod  # tipo de recurso
metadata:  # metadados que identificam o objeto
  labels:  # rótulos do Pod (úteis para seleção e agrupamento)
    run: wisomar-volume1-emptydir  # rótulo chave=valor
  name: wisomar-volume1-emptydir  # nome do Pod
spec:  # especificação desejada do Pod (o que queremos executar)
  containers:  # lista de containers que compõem o Pod
  - image: nginx:latest  # imagem do container (ex: nginx:latest)
    name: webserver # nome do container dentro do Pod
    volumeMounts:  # montagem de volumes no container
    - mountPath: /wisomar # caminho dentro do container onde o volume será montado
      name: wisomar-volume1-emptydir # nome do volume a ser montado 
    args:  # argumentos passados para o processo do container (substitui CMD)
    - sleep  # comando/argumento 1
    - "3600"  # comando/argumento 2 (string, aqui é tempo em segundos)
    resources: # requests/limits de CPU/memória
      requests:  # requests de recursos para o container
        memory: "64Mi"  # request de memória (64 MiB)
        cpu: "0.5"  # request de CPU (300 millicores)
      limits:  # limites de recursos para o container
        memory: "128Mi"  # limite de memória (64 MiB)
        cpu: "1"  # limite de CPU (500 millicores)
  dnsPolicy: ClusterFirst  # política de resolução DNS para o Pod
  restartPolicy: Always  # quando reiniciar containers (Always/Never/OnFailure)
  volumes:  # definição de volumes para o Pod
  - name: wisomar-volume1-emptydir  # nome do volume
    emptyDir:  # tipo de volume (emptyDir = volume temporário em disco
      sizeLimit: "256Mi"  # limite de tamanho do volume (256 MiB)
status: {}  # campo de status (preenchido pelo kubelet/servidor apiserver)


