apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
        version: stable
    spec:
      containers:
        - name: apache
          image: httpd:2.4
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "400m"
              memory: "256Mi"
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
