apiVersion: apps/v1  # versão da API do Kubernetes para recursos core (Pod)
kind: Deployment  # tipo do recurso: Deployment (gerencia réplicas de Pods)
metadata:  # metadados que identificam o objeto (nome, labels, annotations)
  labels:  # rótulos para seleção/organização (úteis em selectors e serviços)
    app: nginx-deployment  # rótulo chave=valor usado para identificar/selecionar esse Deployment
    fruta: banana # rótulo chave=valor adicional para organização
  name: nginx-deployment  # nome único do Deployment no namespace
  namespace: wisomar
spec:  # especificação desejada do Deployment (o que queremos que rode)
  replicas: 10  # número desejado de réplicas de Pods
  revisionHistoryLimit: 10  # número de revisões antigas a serem mantidas
  selector:  # seletor que identifica os Pods gerenciados por este Deployment
    matchLabels:  # rótulos que os Pods devem ter para serem gerenciados
      app: nginx-deployment  # rótulo chave=valor usado para selecionar os Pods
  strategy:   # estratégia de atualização dos Pods (vazio = padrão RollingUpdate ou Recreate)
    type: RollingUpdate # tipo de estratégia de atualização (RollingUpdate ou Recreate)
    rollingUpdate: 
      maxSurge: 3 # número máximo de Pods adicionais durante a atualização
      maxUnavailable: 2 # número máximo de Pods indisponíveis durante a atualização
  template:  # template do Pod (definição dos Pods que serão criados)
    metadata:  # metadados dos Pods (nome, labels, annotations)
      labels:  # rótulos para seleção/organização (úteis em selectors e serviços)
        app: nginx-deployment  # rótulo chave=valor usado para identificar/selecionar esse Pod
    spec:  # especificação desejada do Pod (o que queremos que rode)
      containers:  # lista de containers que compõem este Pod
      - image: nginx:latest # imagem do container (repositório:tag)
        name: nginx  # nome do container dentro do Pod (referência local)
        resources:  # requests/limits de CPU/memória
          requests:  # requests de recursos para o container
            memory: "64Mi"  # request de memória (64 MiB)
            cpu: "0.3"  # request de CPU (300 millicores)
          limits:  # limites de recursos para o container
            memory: "256Mi"  # limite de memória (256 MiB)
            cpu: "0.5"  # limite de CPU (500 millicores)

            