apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wisomar
  name: wisomar-2
spec:
  containers:
  - image: nginx
    name: wisomar
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
